"""
Docusaurus Blog Post Generator and Asset Optimizer.

This module automates the generation of MDX blog posts for Docusaurus from 
structured GitHub Issue Form JSON data. It extracts front matter details 
(title, date, authors, tags), downloads external asset attachments (cover 
photos, inline body images, and multi-file photo albums), converts and compresses 
images into responsive WebP formats, and injects custom React components.

Workflow Steps:
    1. Parses form data and normalizes string strings into URL keys (kebab-case).
    2. Downloads and runs a multi-format image optimizer on cover configurations.
    3. Traverses inline markdown text to collect, downscale, and swap out local assets.
    4. Downloads sequential photo attachments and places them inside an album asset directory.
    5. Calculates text positions to cleanly inject a Docusaurus preview truncation marker.
    6. Compiles and exports a clean MDX file to the repository's native `blog/` folder.

Environment Variables:
    ISSUE_JSON (str): A stringified JSON object generated by `stefanbuck/github-issue-parser` 
        containing the raw form field mappings.

Requirements:
    - Pillow (PIL)
    - python-dateutil

File Structure Impact:
    - Creates layout files at: `blog/{YYYY-MM-DD}-{slug}.mdx`
    - Stores optimized assets at: `static/img/blog/{YYYY-MM-DD}-{slug}/`
"""
import os
import json
import re
import hashlib
import urllib.request
from io import BytesIO
from datetime import datetime
from dateutil import parser
from PIL import Image, ImageOps

# --- Helper functions ---
def optimize_convert_and_hash_images(input_dir, output_dir, max_size=(1920, 1080), quality=80, keep_original_names=False):
    """
    Optimizes, resizes, and converts images in an input directory to WebP format, 
    saving them to an output directory while optionally renaming them using MD5 hashes.

    This function traverses an input folder structure, processes supported images 
    (.jpg, .jpeg, .png, .webp), applies EXIF orientation fixes, resizes them to 
    fit within a maximum bounding box, and saves the output. It purges the original 
    files from disk upon successful processing. It also links processed files back 
    to their original reference URLs if matching '.ref' sidecar files are present.

    Args:
        input_dir (str): Path to the directory containing raw source images.
        output_dir (str): Path to the destination directory where WebP images will be saved.
        max_size (tuple of int, optional): Maximum (width, height) bounding box for resizing 
            using a LANCZOS filter. Defaults to (1920, 1080).
        quality (int, optional): Compression quality parameter for WebP export, 
            ranging from 1 to 100. Defaults to 80.
        keep_original_names (bool, optional): If True, retains the original file base name 
            with a '.webp' extension. If False, names the file using an MD5 hash of its 
            optimized data stream to ensure uniqueness and prevent duplicates. Defaults to False.

    Returns:
        dict: A dictionary mapping original source URLs (extracted from corresponding '.ref' 
            files) to the newly generated file names (e.g., {'https://example.com': 'img_abc123.webp'}).

    Raises:
        No explicit exceptions are raised. Errors encountered during individual file processing 
        or file mutations are intercepted and printed to standard output to allow the loop to continue.
    """
    if not os.path.exists(input_dir):
        return {}
    os.makedirs(output_dir, exist_ok=True)
    valid_extensions = (".jpg", ".jpeg", ".png", ".webp")
    url_to_new_path_map = {}
    
    for root, _, files in os.walk(input_dir):
        for file in files:
            if file.lower().endswith(valid_extensions):
                input_path = os.path.join(root, file)
                relative_path = os.path.relpath(root, input_dir)
                target_folder = os.path.normpath(os.path.join(output_dir, relative_path))
                os.makedirs(target_folder, exist_ok=True)
                try:
                    with Image.open(input_path) as img:
                        img = ImageOps.exif_transpose(img)
                        if img.mode in ("P", "CMYK"):
                            img = img.convert("RGBA")
                        img.thumbnail(max_size, Image.Resampling.LANCZOS)
                        buffer = BytesIO()
                        img.save(buffer, format="WEBP", quality=quality)
                        optimized_data = buffer.getvalue()
                        
                        if keep_original_names:
                            base_name, _ = os.path.splitext(file)
                            output_file_name = f"{base_name}.webp"
                        else:
                            hasher = hashlib.md5(optimized_data)
                            content_hash = hasher.hexdigest()
                            output_file_name = f"img_{content_hash}.webp"
                            
                        output_path = os.path.join(target_folder, output_file_name)
                        
                        if not os.path.exists(output_path):
                            with open(output_path, "wb") as f:
                                f.write(optimized_data)
                                
                        if os.path.exists(input_path):
                            os.remove(input_path)
                            
                        ref_path = os.path.join(root, f"{file}.ref")
                        if os.path.exists(ref_path):
                            with open(ref_path, "r") as ref_f:
                                orig_url = ref_f.read().strip()
                                url_to_new_path_map[orig_url] = output_file_name
                            
                        print(f"[Processed & Purged] {file} -> {output_file_name}")
                except Exception as e:
                    print(f"Failed to process {file}. Error: {e}")
    return url_to_new_path_map

def to_kebab(text):
    """
    Converts a text string into a clean, lowercased kebab-case format 
    suitable for slugs, URLs, or file names.

    The function strips leading/trailing whitespace, converts characters 
    to lowercase, removes non-alphanumeric symbols (excluding spaces 
    and hyphens), collapses consecutive spaces or hyphens into a single 
    dash, and trims leading or trailing dashes from the final output.

    Args:
        text (str or None): The input text string to be slugified.

    Returns:
        str: The transformed kebab-case string, or an empty string 
            if the input is empty or evaluates to None.

    Examples:
        >>> to_kebab("Hello World!")
        'hello-world'
        
        >>> to_kebab("  My  Awesome---Blog  Post  ")
        'my-awesome-blog-post'
        
        >>> to_kebab(None)
        ''
    """
    if not text:
        return ""
    text = text.lower().strip()
    text = re.sub(r"[^a-z0-9\s-]", "", text)
    return re.sub(r"[\s-]+", "-", text).strip("-")

def main():
    """
    Executes the end-to-end extraction, asset optimization, and generation pipeline.

    This function acts as the orchestrator for the script. It loads the source JSON 
    payload from the environment variables, processes author metadata, downloads 
    and compresses all remote image attachments into WebP files, calculates layout 
    break positions for preview truncation, and writes the final, formatted MDX 
    blog post directly to the workspace directory.

    Supported Form Input Fields (extracted from ISSUE_JSON):
        title (str): The raw title text used for front matter and file naming.
        date (str, optional): Overriding target creation date. Defaults to current system date.
        authors (str): Comma-separated list of author identifiers.
        tags (str): Comma-separated list of classification metadata tags.
        cover-photo (str, optional): Markdown link or plain URL pointing to a header image.
        photo-album (str, optional): Clustered markdown links of gallery image attachments.
        blog-content (str): Raw Markdown core narrative containing text and inline graphics.

    Returns:
        None

    Raises:
        KeyError: If the 'ISSUE_JSON' environment variable is entirely missing.
        json.JSONDecodeError: If the provided configuration string contains malformed JSON data.
    """
    # --- SETUP FORMS & METADATA ---
    if "ISSUE_JSON" not in os.environ:
        raise KeyError("Missing 'ISSUE_JSON' environment variable.")

    data = json.loads(os.environ["ISSUE_JSON"])

    # Get safe_title and raw_title from 'title'
    raw_title = data.get("title", "Untitled Post").strip()
    safe_title = raw_title.replace('"', '\\"')

    # Get date_str from 'date' (convert whatever format was entered to YYYY-MM-DD)
    form_date = data.get("date", "").strip()
    current_time = datetime.now()
    date_str = current_time.strftime("%Y-%m-%d")

    if form_date and form_date != "null" and form_date != "_No response_":
        try:
            year_anchor = datetime(current_time.year, 1, 1)
            parsed_date = parser.parse(form_date, default=year_anchor, fuzzy=True)
            date_str = parsed_date.strftime("%Y-%m-%d")
        except Exception as e:
            print(f"[Date Parsing Alert] Fallback used. Error: {e}")

    # Get blogfilename from date_str and slugified raw_title
    slug = to_kebab(raw_title)
    blogfilename = f"{date_str}-{slug}"

    # Get list of raw_authors from 'authors'
    raw_authors = data.get("authors", "")
    if isinstance(raw_authors, str):
        authors = [to_kebab(a) for a in raw_authors.split(",") if a.strip()]
    else:
        authors = [to_kebab(str(raw_authors))]

    # Get raw_tags from kebabed tags (Unit number)
    raw_tags = data.get("tags", "")
    if isinstance(raw_tags, str):
        tags = [to_kebab(t) for t in raw_tags.split(",") if t.strip()]
    else:
        tags = [to_kebab(str(raw_tags))]

    # File locations for processed images
    static_folder = f"static/img/blog/{blogfilename}"
    web_prefix = f"/img/blog/{blogfilename}"

    # --- FETCH AND RUN OPTIMIZER ON COVER PHOTO ---
    cover_input = data.get("cover-photo")
    cover_match = re.search(r'\]\((https?://[^\s\)]+)\)', cover_input)
    cover_url = cover_match.group(1) if cover_match else (cover_input.strip() if cover_input.strip().startswith(('http://', 'https://')) else None)

    cover_line = ""
    if cover_url and cover_url != "null" and cover_url != "_No response_":
        tmp_cover_dir = "/tmp/raw_cover"
        os.makedirs(tmp_cover_dir, exist_ok=True)
        clean_url = cover_url.split("?")
        _, ext = os.path.splitext(clean_url[0])
        if not ext:
            ext = ".jpg"
        raw_cover_path = os.path.join(tmp_cover_dir, f"cover{ext}")
        try:
            urllib.request.urlretrieve(cover_url, raw_cover_path)
            with open(f"{raw_cover_path}.ref", "w") as ref_f:
                ref_f.write("cover")
            optimize_convert_and_hash_images(tmp_cover_dir, static_folder, keep_original_names=True)
            cover_line = f"![Cover Picture]({web_prefix}/cover.webp)"
        except Exception as e:
            print(f"Skipping cover photo download. Error: {e}")

    # --- FETCH AND RUN OPTIMIZER ON ALL ALBUM SLIDES ---
    album_input = data.get("photo-album", "")
    # Extract all markdown image links from the multi-file upload field
    album_matches = re.findall(r'!\[.*?\]\(((https?://[^\s\)]+))\)', album_input)
    has_album = False

    if album_matches:
        tmp_slides_dir = "/tmp/raw_slides"
        os.makedirs(tmp_slides_dir, exist_ok=True)

        # Nest the optimized slides directly inside the target dynamic subfolder path
        slides_static_folder = os.path.join(static_folder, "slides")

        # Download each individual photo into the temporary processing directory
        for index, (full_match_url, clean_match_url) in enumerate(album_matches):
            clean_url = clean_match_url.split("?")[0]
            _, ext = os.path.splitext(clean_url)
            if not ext:
                ext = ".png"

            # Use an index-based name to keep them unique during raw staging
            album_filename = f"album_{index}{ext}"
            album_filepath = os.path.join(tmp_slides_dir, album_filename)

            try:
                urllib.request.urlretrieve(clean_match_url, album_filepath)

                # Create the required sidecar reference file for tracking
                with open(f"{album_filepath}.ref", "w") as ref_f:
                    ref_f.write(clean_match_url)
            except Exception as e:
                print(f"Failed downloading album image {clean_match_url}: {e}")
        
        # Process and optimize the directory full of individual files
        optimize_convert_and_hash_images(tmp_slides_dir, static_folder, keep_original_names=False)
        has_album = True

    # --- PARSE AND DOWNLOAD IMAGES INSIDE BLOG CONTENT ---
    blog_content = data.get("blog-content", "")
    # Find all markdown image URLs inside the text editor field
    inline_matches = re.findall(r'!\[.*?\]\(((https?://[^\s\)]+))\)', blog_content)

    if inline_matches:
        tmp_inline_dir = "/tmp/raw_inline"
        os.makedirs(tmp_inline_dir, exist_ok=True)
        
        for index, (full_match_url, clean_match_url) in enumerate(inline_matches):
            clean_url = clean_match_url.split("?")
            _, ext = os.path.splitext(clean_url[0])
            if not ext:
                ext = ".png"
            inline_filename = f"inline_{index}{ext}"
            inline_filepath = os.path.join(tmp_inline_dir, inline_filename)
            
            try:
                urllib.request.urlretrieve(clean_match_url, inline_filepath)
                with open(f"{inline_filepath}.ref", "w") as ref_f:
                    ref_f.write(clean_match_url)
            except Exception as e:
                print(f"Failed downloading inline image {clean_match_url}: {e}")
                
        inline_map = optimize_convert_and_hash_images(tmp_inline_dir, static_folder, keep_original_names=False)
        
        # Swap original markdown URLs with the newly generated WebP image routes
        for orig_url, webp_filename in inline_map.items():
            blog_content = blog_content.replace(orig_url, f"{web_prefix}/{webp_filename}")

    # --- WRITE OUT THE MDX POST FILE ---
    os.makedirs("blog", exist_ok=True)
    mdx_filepath = f"blog/{blogfilename}.mdx"

    front_matter_authors = ", ".join(authors)
    front_matter_tags = ", ".join(tags)

    # Inject the dynamic PhotoAlbumGallery component into the template if an album was uploaded
    import_line = ""
    album_component_markdown = ""
    if has_album:
        import_line = "import PhotoAlbumGallery from '@site/src/components/PhotoAlbumGallery';\n\n"
        album_component_markdown = f"""\n\n## Photo Album\n\n<PhotoAlbumGallery\n    context={{require.context('/img/blog/{blogfilename}/slides', false, /\\.(png|jpe?g|svg|webp)$/)}}\n/>\n"""

    # Handle Docusaurus preview truncation, ignoring non-text layout blocks
    # Split by double newlines to isolate paragraphs
    MAX_PARAGRAPH_CHARS = 350 # Fallback limit for excessively long paragraphs
    paragraphs = blog_content.split("\n\n")

    first_text_index = None
    has_subsequent_content = False

    # Step A: Locate the first true text block that isn't an image, component, or import statement
    for idx, p in enumerate(paragraphs):
        stripped_p = p.strip()
        
        # Combined skip condition for empty blocks, images, code, lists, and headings
        if (not stripped_p or 
            stripped_p.startswith(("![", "<img", "import ", "export ", "|", "```")) or 
            re.match(r'^#{1,6}\s', stripped_p) or 
            re.match(r'^[\-\*\+]\s', stripped_p) or 
            re.match(r'^\d+\.\s', stripped_p)):
            continue
            
        # Found the first true text block!
        if first_text_index is None:
            first_text_index = idx
        else:
            # We found a text block, and there is more content after it
            has_subsequent_content = True
            break

    # Step B: Apply Truncation Tag (with character-limit safety fallback)
    if first_text_index is not None:
        target_paragraph = paragraphs[first_text_index]
        
        # Check if the paragraph is excessively long
        if len(target_paragraph) > MAX_PARAGRAPH_CHARS:
            # Find the closest sentence end near our maximum character threshold
            # It scans for periods, exclamation marks, or question marks followed by a space
            sentence_ends = [m.end() for m in re.finditer(r'[\.\!\?]\s', target_paragraph[:MAX_PARAGRAPH_CHARS + 50])]
            
            if sentence_ends:
                # Split at the last complete sentence within our threshold window
                split_point = sentence_ends[-1]
                truncated_part = target_paragraph[:split_point].strip()
                remaining_part = target_paragraph[split_point:].strip()
                
                # Re-structure the paragraph to house the tag internally
                paragraphs[first_text_index] = f"{truncated_part}\n\n{{/* truncate */}}\n\n{remaining_part}"
            else:
                # Hard fallback if no punctuation is found: split exactly at the character count
                truncated_part = target_paragraph[:MAX_PARAGRAPH_CHARS].strip()
                remaining_part = target_paragraph[MAX_PARAGRAPH_CHARS:].strip()
                paragraphs[first_text_index] = f"{truncated_part}...\n\n{{/* truncate */}}\n\n...{remaining_part}"
        
        # If the paragraph is normal length and there's more text coming later, append tag after it
        elif has_subsequent_content:
            paragraphs.insert(first_text_index + 1, "{/* truncate */}")

        blog_content = "\n\n".join(paragraphs)
        
    with open(mdx_filepath, "w", encoding="utf-8") as mdx_file:
        mdx_file.write(f"---\n")
        mdx_file.write(f"title: \"{safe_title}\"\n")
        mdx_file.write(f"date: {date_str}\n")
        if authors:
            mdx_file.write(f"authors: [{front_matter_authors}]\n")
        if tags:
            mdx_file.write(f"tags: [{front_matter_tags}]\n")
        mdx_file.write(f"---\n\n")
        if import_line:
            mdx_file.write(import_line)
        if cover_line:
            mdx_file.write(f"{cover_line}\n\n")
        mdx_file.write(f"{blog_content}")
        mdx_file.write(album_component_markdown)

    print(f"Successfully generated blog file at: {mdx_filepath}")

if __name__ == "__main__":
    main()