"""
Docusaurus Document Generator and Asset Optimizer.

This module automates the generation of MDX documents for Docusaurus from 
structured GitHub Issue Form JSON data. It extracts front matter details 
(title, description), downloads external asset attachments (inline body images
and files), and converts and compresses images into responsive WebP formats.

Workflow Steps:
    1. Parses form data and normalizes string strings into URL keys (kebab-case).
    2. Traverses inline markdown text to collect, downscale, and swap out local assets.
    3. Downloads sequential photo attachments and places them inside an album asset directory.
    4. Compiles and exports a clean MDX file to the repository's native `docs/` folder.

Environment Variables:
    ISSUE_JSON (str): A stringified JSON object generated by `stefanbuck/github-issue-parser` 
        containing the raw form field mappings.

Requirements:
    - Pillow (PIL)

File Structure Impact:
    - Creates layout files at: `docs/{unit}/{slug}.mdx`
    - Stores optimized assets at: `static/img/docs/{unit}/{slug}/`
"""
import os
import json
import re
import hashlib
import urllib.request
from io import BytesIO
from PIL import Image, ImageOps

# --- Helper functions ---
def optimize_convert_and_hash_images(input_dir, output_dir, max_size=(1920, 1080), quality=80, keep_original_names=False):
    """
    Optimizes, resizes, and converts images in an input directory to WebP format, 
    saving them to an output directory while optionally renaming them using MD5 hashes.

    This function traverses an input folder structure, processes supported images 
    (.jpg, .jpeg, .png, .webp), applies EXIF orientation fixes, resizes them to 
    fit within a maximum bounding box, and saves the output. It purges the original 
    files from disk upon successful processing. It also links processed files back 
    to their original reference URLs if matching '.ref' sidecar files are present.

    Args:
        input_dir (str): Path to the directory containing raw source images.
        output_dir (str): Path to the destination directory where WebP images will be saved.
        max_size (tuple of int, optional): Maximum (width, height) bounding box for resizing 
            using a LANCZOS filter. Defaults to (1920, 1080).
        quality (int, optional): Compression quality parameter for WebP export, 
            ranging from 1 to 100. Defaults to 80.
        keep_original_names (bool, optional): If True, retains the original file base name 
            with a '.webp' extension. If False, names the file using an MD5 hash of its 
            optimized data stream to ensure uniqueness and prevent duplicates. Defaults to False.

    Returns:
        dict: A dictionary mapping original source URLs (extracted from corresponding '.ref' 
            files) to the newly generated file names (e.g., {'https://example.com': 'img_abc123.webp'}).

    Raises:
        No explicit exceptions are raised. Errors encountered during individual file processing 
        or file mutations are intercepted and printed to standard output to allow the loop to continue.
    """
    if not os.path.exists(input_dir):
        return {}
    os.makedirs(output_dir, exist_ok=True)
    valid_extensions = (".jpg", ".jpeg", ".png", ".webp")
    url_to_new_path_map = {}
    
    for root, _, files in os.walk(input_dir):
        for file in files:
            if file.lower().endswith(valid_extensions):
                input_path = os.path.join(root, file)
                relative_path = os.path.relpath(root, input_dir)
                target_folder = os.path.normpath(os.path.join(output_dir, relative_path))
                os.makedirs(target_folder, exist_ok=True)
                try:
                    with Image.open(input_path) as img:
                        img = ImageOps.exif_transpose(img)
                        if img.mode in ("P", "CMYK"):
                            img = img.convert("RGBA")
                        img.thumbnail(max_size, Image.Resampling.LANCZOS)
                        buffer = BytesIO()
                        img.save(buffer, format="WEBP", quality=quality)
                        optimized_data = buffer.getvalue()
                        
                        if keep_original_names:
                            base_name, _ = os.path.splitext(file)
                            output_file_name = f"{base_name}.webp"
                        else:
                            hasher = hashlib.md5(optimized_data)
                            content_hash = hasher.hexdigest()
                            output_file_name = f"img_{content_hash}.webp"
                            
                        output_path = os.path.join(target_folder, output_file_name)
                        
                        if not os.path.exists(output_path):
                            with open(output_path, "wb") as f:
                                f.write(optimized_data)
                                
                        if os.path.exists(input_path):
                            os.remove(input_path)
                            
                        ref_path = os.path.join(root, f"{file}.ref")
                        if os.path.exists(ref_path):
                            with open(ref_path, "r") as ref_f:
                                orig_url = ref_f.read().strip()
                                url_to_new_path_map[orig_url] = output_file_name
                            
                        print(f"[Processed & Purged] {file} -> {output_file_name}")
                except Exception as e:
                    print(f"Failed to process {file}. Error: {e}")
    return url_to_new_path_map

def to_kebab(text):
    """
    Converts a text string into a clean, lowercased kebab-case format 
    suitable for slugs, URLs, or file names.

    The function strips leading/trailing whitespace, converts characters 
    to lowercase, removes non-alphanumeric symbols (excluding spaces 
    and hyphens), collapses consecutive spaces or hyphens into a single 
    dash, and trims leading or trailing dashes from the final output.

    Args:
        text (str or None): The input text string to be slugified.

    Returns:
        str: The transformed kebab-case string, or an empty string 
            if the input is empty or evaluates to None.

    Examples:
        >>> to_kebab("Hello World!")
        'hello-world'
        
        >>> to_kebab("  My  Awesome---Blog  Post  ")
        'my-awesome-blog-post'
        
        >>> to_kebab(None)
        ''
    """
    if not text:
        return ""
    text = text.lower().strip()
    text = re.sub(r"[^a-z0-9\s-]", "", text)
    return re.sub(r"[\s-]+", "-", text).strip("-")

def main():
    """
    Executes the end-to-end extraction, asset optimization, and generation pipeline.

    This function acts as the orchestrator for the script. It loads the source JSON 
    payload from the environment variables, processes metadata, downloads 
    and compresses all remote image attachments into WebP files, and writes the final, formatted MDX 
    document directly to the workspace directory.

    Supported Form Input Fields (extracted from ISSUE_JSON):
        title (str): The raw title text used for front matter and file naming.
        description (str): A description of the new document that will be used in metadata
        unit (str): unit with which to classify this document.
        doc-content (str): Raw Markdown core narrative containing text and inline graphics.
      
    Returns:
        None

    Raises:
        KeyError: If the 'ISSUE_JSON' environment variable is entirely missing.
        json.JSONDecodeError: If the provided configuration string contains malformed JSON data.
    """
    # --- SETUP FORMS & METADATA ---
    if "ISSUE_JSON" not in os.environ:
        raise KeyError("Missing 'ISSUE_JSON' environment variable.")

    data = json.loads(os.environ["ISSUE_JSON"])
    
    # Get safe_title and raw_title from 'title'
    raw_title = data.get("title", "Untitled Document").strip()
    description = data.get("description", "").strip()
    selected_unit = data.get("unit", "General").strip()
    doc_content = data.get("doc-content", "")

    # Clean strings for Markdown front matter
    safe_title = raw_title.replace('"', '\\"')
    safe_description = description.replace('"', '\\"')

    # Generate slugified file name
    slug = to_kebab(raw_title)

    # --- DETERMINE TARGET DIRECTORY PATH ---
    # Convert unit to kebab case for safe folder names (e.g., "troop-331")
    unit_folder = to_kebab(selected_unit)
    docs_directory = f"docs/{unit_folder}"
    os.makedirs(docs_directory, exist_ok=True)

    # Establish asset pathways for uploaded inline document media
    static_folder = f"static/img/docs/{unit_folder}/{slug}"
    web_prefix = f"/img/docs/{unit_folder}/{slug}"

    # --- PARSE AND DOWNLOAD INLINE IMAGES ---
    inline_matches = re.findall(r'!\[.*?\]\(((https?://[^\s\)]+))\)', doc_content)

    if inline_matches:
        tmp_inline_dir = "/tmp/raw_doc_inline"
        os.makedirs(tmp_inline_dir, exist_ok=True)

        for index, (full_match_url, clean_match_url) in enumerate(inline_matches):
            clean_url = clean_match_url.split("?")[0]
            _, ext = os.path.splitext(clean_url)
            if not ext:
                ext = ".png"

            inline_filename = f"image_{index}{ext}"
            inline_filepath = os.path.join(tmp_inline_dir, inline_filename)

            try:
                urllib.request.urlretrieve(clean_match_url, inline_filepath)
                with open(f"{inline_filepath}.ref", "w") as ref_f:
                    ref_f.write(clean_match_url)
            except Exception as e:
                print(f"Failed downloading inline image {clean_match_url}: {e}")

            # Optimize downloads
            inline_map = optimize_convert_and_hash_images(tmp_inline_dir, static_folder, keep_original_names=False)

            # Swap out raw URLs inside text area with local static paths
            for orig_url, webp_filename in inline_map.items():
                doc_content = doc_content.replace(orig_url, f"{web_prefix}/{webp_filename}")
            
            # --- BUILD FRONT MATTER AND WRITING THE MARKDOWN ---
            markdown_path = f"{docs_directory}/{slug}.mdx"

            # Assemble metadata block required by Docusaurus
            front_matter = [
                "---",
                f'title: "{safe_title}"',
                f'description: "{safe_description}"',
                "---",
                "",
            ]

            doc_payload = "\n".join(front_matter) + doc_content

            with open(markdown_path, "w", encoding="utf-8") as doc_file:
                doc_file.write(doc_payload)

            print(f"[Pipeline Complete] Document successfully written to: {markdown_path}")
