/**
 * @file sidebarsCookbook.js
 * @description Sidebar configuration module dedicated to the multi-instance Cookbook section.
 * Programmatically maps the filesystem directory hierarchy into an automated navigation index
 * for managing recipes, cooking instructions, and campsite meal guides.
 * 
 * @environment Node.js (Build-time compilation script)
 * @see {@link https://docusaurus.io | Docusaurus Sidebar Configuration}
 */

/**
 * Structural navigation tree mapping out cookbook menu layers.
 * 
 * @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 * @property {Array<Object>} cookbookSidebar - Specialized collection structure using filesystem rules.
 */
const sidebars = {
  cookbookSidebar: [{ type: "autogenerated", dirName: "." }],
};

export default sidebars;
