/**
 * @file sidebarDocs.js
 * @description Master navigation config module for the Docusaurus site structure.
 * Maps localized scouting unit directories (`dirName`) into clean sidebar paths.
 * Uses `generated-index` links to dynamically handle directory landings, ensuring 
 * the site builds successfully even if unit folders lack standalone index files.
 * 
 * @environment Node.js (Build-time static generation script)
 * @see {@link https://docusaurus.io | Docusaurus Sidebar Configuration Docs}
 */

/**
 * Global navigation tree matching our scouting organizational infrastructure.
 * 
 * @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */
export default {
    // Defines the individual sidebar identifier name referenced inside docusaurus.config.js
    sidebarDocs: [
        // ---------------------------------------------------------------------
        // CATEGORY 1: General cross-unit documentation mapping block
        // ---------------------------------------------------------------------
        {
            type: 'category',               // Renders an expandable multi-item folder dropdown block
            label: 'General Documents',     // Public text header label displayed inside the UI sidebar
            link: {
                type: 'generated-index',    // Instructs Docusaurus to auto-generate a landing dashboard view page
                title: 'General Documents', // Headline title text used inside the auto-generated dashboard view
                description: 'General documents applicable to multiple units', // Explanatory subtitle string
                slug: '/general'            // Base web URL route path mapping address for this index node
            },
            items: [
                {
                    type: 'autogenerated',  // Enables automatic scanning of your local file directory trees
                    dirName: 'general'      // Recursively imports files located inside the "docs/general/" path
                }
            ]
        },
        // ---------------------------------------------------------------------
        // CATEGORY 2: Crew 303 documentation folder block
        // ---------------------------------------------------------------------
        {
            type: 'category',
            label: 'Crew 303',
            link: {
                type: 'generated-index',
                title: 'Crew 303',
                description: 'Crew 303 documents',
                slug: '/crew-303'
            },
            items: [
                {
                    type: 'autogenerated',
                    dirName: 'crew-303'     // Recursively imports files located inside the "docs/crew-303/" path
                }
            ]
        },
        // ---------------------------------------------------------------------
        // CATEGORY 3: Pack 303 documentation folder block
        // ---------------------------------------------------------------------
        {
            type: 'category',
            label: 'Pack 303',
            link: {
                type: 'generated-index',
                title: 'Pack 303',
                description: 'Pack 303 documents',
                slug: '/pack-303'
            },
            items: [
                {
                    type: 'autogenerated',
                    dirName: 'pack-303'     // Recursively imports files located inside the "docs/pack-303/" path
                }
            ]
        },
        // ---------------------------------------------------------------------
        // CATEGORY 4: Troop 303 documentation folder block
        // ---------------------------------------------------------------------
        {
            type: 'category',
            label: 'Troop 303',
            link: {
                type: 'generated-index',
                title: 'Troop 303',
                description: 'Troop 303 documents',
                slug: '/troop-303'
            },
            items: [
                {
                    type: 'autogenerated',
                    dirName: 'troop-303'    // Recursively imports files located inside the "docs/troop-303/" path
                }
            ]
        },
        // ---------------------------------------------------------------------
        // CATEGORY 5: Troop 331 documentation folder block
        // ---------------------------------------------------------------------
        {
            type: 'category',
            label: 'Troop 331',
            link: {
                type: 'generated-index',
                title: 'Troop 331',
                description: 'Troop 331 documents',
                slug: '/troop-331'
            },
            items: [
                {
                    type: 'autogenerated',
                    dirName: 'troop-331'    // Recursively imports files located inside the "docs/troop-331/" path
                }
            ]
        }
    ]
}
