/**
 * @file sidebarDocs.js
 * @description Master navigation config module for the Docusaurus site structure.
 * Maps localized scouting unit directories (`dirName`) into clean sidebar paths.
 * Uses `generated-index` links to dynamically handle directory landings, ensuring 
 * the site builds successfully even if unit folders lack standalone index files.
 * 
 * @environment Node.js (Build-time static generation script)
 * @see {@link https://docusaurus.io | Docusaurus Sidebar Configuration Docs}
 */

/**
 * Global navigation tree matching our scouting organizational infrastructure.
 * 
 * @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */
export default {
    sidebarDocs: [
        {
            type: 'category',
            label: 'General Documents',
            link: {
                type: 'generated-index',
                title: 'General Documents',
                description: 'General documents applicable to multiple units',
                slug: '/general-docs'
            },
            items: [
                {
                    type: 'autogenerated',
                    dirName: 'general-docs'
                }
            ]
        },
        {
            type: 'category',
            label: 'Crew 303',
            link: {
                type: 'generated-index',
                title: 'Crew 303',
                description: 'Crew 303 documents',
                slug: '/crew-303'
            },
            items: [
                {
                    type: 'autogenerated',
                    dirName: 'crew-303'
                }
            ]
        },
        {
            type: 'category',
            label: 'Pack 303',
            link: {
                type: 'generated-index',
                title: 'Pack 303',
                description: 'Pack 303 documents',
                slug: '/pack-303'
            },
            items: [
                {
                    type: 'autogenerated',
                    dirName: 'pack-303'
                }
            ]
        },
        {
            type: 'category',
            label: 'Troop 303',
            link: {
                type: 'generated-index',
                title: 'Troop 303',
                description: 'Troop 303 documents',
                slug: '/troop-303'
            },
            items: [
                {
                    type: 'autogenerated',
                    dirName: 'troop-303'
                }
            ]
        },
        {
            type: 'category',
            label: 'Troop 331',
            link: {
                type: 'generated-index',
                title: 'Troop 331',
                description: 'Troop 331 documents',
                slug: '/troop-331'
            },
            items: [
                {
                    type: 'autogenerated',
                    dirName: 'troop-331'
                }
            ]
        }
    ]
}