/**
 * @file sidebars.js
 * @description Sidebar configuration module for the Docusaurus documentation engine.
 * Utilizes programmatic autogeneration to map the target folder's directory structure 
 * directly into the sidebar menu navigation hierarchy without manual list curation.
 * 
 * @environment Node.js (Build-time compilation script)
 * @see {@link https://docusaurus.io | Docusaurus Sidebar Configuration}
 */

/**
 * Structural navigation tree mapping out documentation layouts.
 * 
 * @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 * @property {Array<Object>} docsSidebar - Main navigation array using filesystem scaffolding rules.
 */
const sidebars = { docsSidebar: [{ type: "autogenerated", dirName: "." }] };

export default sidebars;
