name: New Blog Post
description: "Add a new post to the blog"
labels: ["blog"]
title: "[New Blog Post]"
body:
  - type: markdown
    attributes:
      value: |
        **The title above is just for internal use. Please don't change it**

        # Creating new blog post

        Fill out this form and click "Create" below to submit a new blog post.
        After submitting your post, it will be reviewed by the webmaster before
        being posted to the website.
  - type: input
    id: title
    attributes:
      label: "Blog Title"
      description: |
        Title for your post

        This should include the campout/adventure/event if thats what this post
        is about!
      placeholder: "Our Recent Adventures"
    validations:
      required: true
  - type: input
    id: date
    attributes:
      label: "Post Date"
      description: |
        Date for your blog post

        If this is left empty, today's date will be used.
      placeholder: YYYY-MM-DD
    validations:
      required: false
  - type: dropdown
    id: authors
    attributes:
      label: "Authors"
      description: "Select author(s) of this post"
      multiple: true
      options:
        # AUTHOR_START
        - Chris Koczan
        - Benjamin Shover
        # AUTHOR_END
    validations:
      required: true
  - type: markdown
    attributes:
      value: |
        If your name is not in the list of authors, please submit a request to
        add your name to the list of authors here:

        [New Author Request](https://github.com/scouting331/scoutSite/issues/new?template=03-new-blog-author.yml)
  - type: dropdown
    id: tags
    attributes:
      label: "Unit"
      description: |
        Select the unit(s) to associate this post with.

        Multiple units may be selected.
      multiple: true
      options:
        - Troop 303
        - Troop 331
        - Crew 303
        - Pack 303
    validations:
      required: true
  - type: upload
    id: cover-photo
    attributes:
      label: "Cover Photo"
      description: |
        Photo shown at top of your blog post and on the homepage card

        **NOTE**: There is no way to limit the number of files in this space. Please
        only upload 1 photo. If multiple photos are uploaded, the script will
        simply choose one photo and discard the rest.
    validations:
      required: false
      accept: ".png, .jpg, .jpeg, .gif, .svg, .webp"
  - type: upload
    id: photo-album
    attributes:
      label: "Photo Album"
      description: |
        If you want to include a photo album upload all of the photos you want
        included here.
        
        **NOTE**: If the file is too big (>25 Mb), the photo will need to be resized
        before being uploaded.
    validations:
      required: false
      accept: ".png, .jpg, .jpeg, .gif, .svg, .webp"
  - type: textarea
    id: blog-content
    attributes:
      label: "Blog Text"
      description: |
        Write your blog post here!
      placeholder: "Blog text here..."
    validations:
      required: true
  - type: markdown
    attributes:
      value: |
        **Please don't edit any of the other options!**
