name: New Blog Post
description: "Add a new post to the blog"
labels: ["blog"]
title: ""
body:
  - type: markdown
    attributes:
      value: |
        **The title above will be the title of your blog post**

        Fill out this form and click "Create" below to submit a new blog post.
        After submitting your post, it will be reviewed by the webmaster before
        being posted to the website.
  - type: dropdown
    id: authors
    attributes:
      label: "Select authors"
      description: "Use new author issue form if the author isn't listed here"
      multiple: true
      options:
        # AUTHOR_START
        - Christopher Koczan
        - Benjamin Shover
        # AUTHOR_END
    validations:
      required: true
  - type: checkboxes
    id: tags
    attributes:
      label: Unit
      description: "Select the unit(s) to associate this post with"
      options:
        - label: Troop 303
        - label: Troop 331
        - label: Crew 303
        - label: Pack 303
    validations:
      required: true
  - type: upload
    id: cover-photo
    attributes:
      label: "Cover Photo"
      description: "Photo shown at top of your blog post and on the homepage card"
    validations:
      required: false
      accept: ".png, .jpg, .jpeg, .gif, .svg, .webp"
  - type: upload
    id: photo-album
    attributes:
      label: "Photo Album"
      description: "Compress folder of photos as a zip file before uploading. If the file is too big (>25 Mb), the photo album will need to be added manually (see Mr. Shover)"
    validations:
      required: false
      accept: ".zip"
  - type: textarea
    id: blog-content
    attributes:
      label: "Blog Text"
      description: "Write your blog post here!"
      placeholder: "Blog text here..."
      render: text
    validations:
      required: true
